
local LuaRS232=require("LuaRS232")
local UART=LuaRS232.SerialPortOpen("COM5")
UART:Send("What's up doc\r\n")
print("Waiting 5 seconds (send it messages meanwhile)")
LuaRS232.Sleep(5000)
print("Done waiting")
local got=UART:Receive()
print("Received: \""..got.."\"")
print("Sleep some more")
UART:Sleep(5000)
local got=UART:Receive()
print("Received: \""..got.."\"")
